urls.py
from django.conf.urls.defaults import *
from django.contrib import admin

import settings

admin.autodiscover()

urlpatterns = patterns('',
    (r"^_admin/(.*)$", admin.site.root),

    (r"^$", 'travelist.views.index'),

    (r"^account/login/$", 'travelist.account.login'),
    (r"^account/logout/$", 'travelist.account.logout'),
    (r"^account/register/$", 'travelist.account.register'),
    (r"^account/confirm-email/$", 'travelist.account.confirm_email'),
    (r"^account/profile/$", 'travelist.account.profile'),
    (r"^account/profile/connect/$", 'travelist.account.profile_connect'),

    (r"^help/(?P<section>\w+)/$", 'travelist.help.view'),

    (r"^suggestions/new/$", 'travelist.suggestion.new'),

    (r"^notifications/$", 'travelist.notification.all'),
    (r"^notifications/(?P<id>\d+)/$", 'travelist.notification.action'),

    (r"^people/(?P<username>\w+)/$", 'travelist.user.profile'),
    (r"^people/(?P<username>\w+)/friends/$", 'travelist.user.friends'),
    (r"^people/(?P<username>\w+)/relationship/$", 'travelist.user.relationship'),
    (r"^people/(?P<username>\w+)/map/$", 'travelist.user.map'),
    (r"^people/(?P<username>\w+)/stats/$", 'travelist.user.stats'),

    (r"^places/search/$", 'travelist.place.search'),
    (r"^places/suggest/$", 'travelist.place.suggest'),
    (r"^places/(?P<id>\d+)(-[\w-]+)?/$", 'travelist.place.view'),
    (r"^places/(?P<id>\d+)/edit/$", 'travelist.place.edit'),
    (r"^places/(?P<id>\d+)/rate/$", 'travelist.place.rate'),
    (r"^places/(?P<place_id>\d+)/comments/new/$", 'travelist.place.comment_new'),
    (r"^places/(?P<place_id>\d+)/comments/(?P<id>\d+)/delete/$", 'travelist.place.comment_delete'),

    (r"^accommodations/(?P<id>\d+)(-[\w-]+)?/$", 'travelist.accommodation.view'),
    (r"^accommodations/(?P<id>\d+)/edit/$", 'travelist.accommodation.edit'),
    (r"^accommodations/(?P<id>\d+)/rate/$", 'travelist.accommodation.rate'),
    (r"^accommodations/(?P<accommodation_id>\d+)/comments/new/$", 'travelist.accommodation.comment_new'),
    (r"^accommodations/(?P<accommodation_id>\d+)/comments/(?P<id>\d+)/delete/$", 'travelist.accommodation.comment_delete'),

    (r"^trips/new/$", 'travelist.trip.new'),
    (r"^trips/(?P<id>\d+)(-[\w-]+)?/$", 'travelist.trip.view'),
    (r"^trips/(?P<id>\d+)/details/$", 'travelist.trip.details'),
    (r"^trips/(?P<id>\d+)/points/$", 'travelist.trip.points'),
    (r"^trips/(?P<id>\d+)/edit/$", 'travelist.trip.edit'),
    (r"^trips/(?P<id>\d+)/delete/$", 'travelist.trip.delete'),
    (r"^trips/(?P<id>\d+)/journal/$", 'travelist.trip.journal'),

    (r"^trips/(?P<username>\w+)/$", 'travelist.trip.user'),

    (r"^trips/(?P<id>\d+)/links/new/$", 'travelist.trip.new_links'),
    (r"^trips/(?P<id>\d+)/links/(?P<link_id>\d+)/delete/$", 'travelist.trip.delete_link'),

    (r"^trips/(?P<trip_id>\d+)/annotations/(?P<id>\d+)/$", 'travelist.annotation.view'),
    (r"^trips/(?P<trip_id>\d+)/annotations/new/$", 'travelist.annotation.new'),
    (r"^trips/(?P<trip_id>\d+)/annotations/(?P<id>\d+)/edit/$", 'travelist.annotation.edit'),
    (r"^trips/(?P<trip_id>\d+)/annotations/(?P<id>\d+)/delete/$", 'travelist.annotation.delete'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r"^media/(?P<path>.*)$", 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

travelist/models.py
import os
from datetime import date
from datetime import datetime

from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib.gis.db import models

import settings

from travelist import utils
from travelist.utils import cached_property

class Country(models.Model):
    code = models.CharField(max_length=2)
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "countries"

    def __unicode__(self):
        return "%s (%s)" % (self.name, self.code)

    def __cmp__(self, other):
        return cmp(self.name, other.name)

class AdministrativeDivision(models.Model):
    code = models.CharField(max_length=20)
    name = models.CharField(max_length=100)
    country = models.ForeignKey(Country)

    class Meta:
        unique_together = ('country', 'code')

    def __unicode__(self):
        return "%s (%s)" % (self.name, self.code)

Rating = utils.Enum([(1, "Bad"),
                     (2, "Average"),
                     (3, "Good")])

Source = utils.Enum([(1, "Manual"),
                     (2, "Geonames")])

class Place(models.Model):
    url_prefix = 'places'

    source = models.IntegerField(choices=Source.choices)
    external_code = models.IntegerField()
    name = models.CharField(max_length=100)
    name_ascii = models.CharField(max_length=100)
    country = models.ForeignKey(Country)
    administrative_division = models.ForeignKey(AdministrativeDivision, null=True)
    coords = models.PointField()
    wiki_content = models.TextField(blank=True)
    date_modified_external = models.DateTimeField(blank=True, null=True)

    def __unicode__(self):
        return self.display_name

    def __cmp__(self, other):
        return cmp(self.name, other.name)

    @property
    def source_h(self):
        return Source.get_description(self.source)

    def get_absolute_url(self):
        return "/places/%s-%s/" % (self.id, utils.clean_title_for_url(self.display_name))

    @cached_property
    def display_name(self):
        name = self.name
        if self.administrative_division:
            if self.name != self.administrative_division.name:
                name += ", %s" % self.administrative_division.name
        name += ", %s" % self.country.name
        return name

    @cached_property
    def ratings(self):
        counts = PlaceRating.objects.filter(place=self).values('value').annotate(models.Count('value'))
        ratings = dict((r, 0) for r in Rating.items)
        ratings.update(dict([(Rating.get_name(c['value']), c['value__count']) for c in counts]))
        return ratings

class PlaceName(models.Model):
    place = models.ForeignKey(Place)
    source = models.IntegerField(choices=Source.choices)
    name = models.CharField(max_length=200, db_index=True)

class PlaceSuggestion(models.Model):
    user = models.ForeignKey(User)
    date = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=100)
    comments = models.TextField()

    def __unicode__(self):
        return self.name

class PlaceHist(models.Model):
    place = models.ForeignKey(Place)
    wiki_content = models.TextField()
    user = models.ForeignKey(User)
    date_added = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.place.display_name

class PlaceRating(models.Model):
    place = models.ForeignKey(Place)
    user = models.ForeignKey(User)
    value = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)

class PlaceComment(models.Model):
    place = models.ForeignKey(Place)
    user = models.ForeignKey(User)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date_added']

class Accommodation(models.Model):
    url_prefix = 'accommodations'

    name = models.CharField(max_length=100)
    place = models.ForeignKey(Place, editable=False)
    wiki_content = models.TextField(blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('name', 'place')

    def __unicode__(self):
        return "%s, %s" % (self.name, self.place.name)

    def get_absolute_url(self):
        title = utils.clean_title_for_url(self.name)
        return "/accommodations/%s%s%s/" % (self.id, "-" if title else "", title)

    @cached_property
    def ratings(self):
        counts = AccommodationRating.objects.filter(accommodation=self).values('value').annotate(models.Count('value'))
        ratings = dict((r, 0) for r in Rating.items)
        ratings.update(dict([(Rating.get_name(c['value']), c['value__count']) for c in counts]))
        return ratings

class AccommodationHist(models.Model):
    accommodation = models.ForeignKey(Accommodation)
    wiki_content = models.TextField()
    user = models.ForeignKey(User)
    date_added = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.accommodation.name

class AccommodationRating(models.Model):
    accommodation = models.ForeignKey(Accommodation)
    user = models.ForeignKey(User)
    value = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)

class AccommodationComment(models.Model):
    accommodation = models.ForeignKey(Accommodation)
    user = models.ForeignKey(User)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date_added']

UserLevel = utils.Enum([(1, "Basic"),
                        (2, "Pro")])

def _get_profile_picture_location(profile, name):
    username = profile.user.username
    return "pp/%s/%s%s" % (username[0], username, os.path.splitext(name)[1])

class UserProfile(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    level = models.IntegerField(choices=UserLevel.choices, default=UserLevel.BASIC)
    confirmation_key = models.CharField(max_length=40)
    email_confirmed = models.BooleanField(default=False)
    name = models.CharField(max_length=50, blank=True)
    current_location = models.ForeignKey(Place, blank=True, null=True)
    about = models.TextField(blank=True)
    picture = models.ImageField(blank=True, upload_to=_get_profile_picture_location)
    twitter_username = models.CharField(max_length=40, blank=True, null=True, db_index=True)
    flickr_userid = models.CharField(max_length=40, blank=True, null=True, db_index=True)
    date_modified = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.user.username

    @property
    def picture_thumbnail_path(self):
        if self.picture:
            split = os.path.splitext(self.picture.path)
            return "".join([split[0], ".thumbnail", split[1]])

    @property
    def picture_thumbnail_url(self):
        if self.picture:
            try:
                dot_index = self.picture.url.rindex(".")
            except ValueError:
                return "%s.thumbnail" % self.picture.url
            return "%s.thumbnail%s" % (self.picture.url[:dot_index], self.picture.url[dot_index:])
        else:
            return "%spp/default.png" % settings.MEDIA_URL

RelationshipStatus = utils.Enum([(0, "Pending"),
                                 (1, "Confirmed")])

class UserRelationship(models.Model):
    class __metaclass__(models.Model.__metaclass__):
         def __init__(cls, name, bases, classdict):
             models.Model.__metaclass__.__init__(cls, name, bases, classdict)

             # extend django.contrib.auth.models.User class
             User.get_relationship = lambda self, other: \
                 UserRelationship.objects.get(Q(lhs=self, rhs=other) | Q(lhs=other, rhs=self))
             User.get_confirmed_relationships = lambda self: \
                 UserRelationship.objects.filter(Q(lhs=self) | Q(rhs=self), status=RelationshipStatus.CONFIRMED)
             def get_friends(self):
                 relationships = self.get_confirmed_relationships()
                 friend_ids = [str(r.lhs_id) if r.lhs_id != self.id else str(r.rhs_id) for r in relationships]
                 return [p.user for p in UserProfile.objects.filter(user__in=friend_ids).select_related('user')]
             User.get_friends = get_friends
             def get_relationship_status(self, other):
                 is_self = self == other
                 if is_self:
                     is_friend = is_friend_pending = False
                 elif self.is_anonymous() or other.is_anonymous():
                     is_friend = is_friend_pending = False
                 else:
                     try:
                         relationship = self.get_relationship(other)
                         is_friend = relationship.status == RelationshipStatus.CONFIRMED
                         is_friend_pending = relationship.status == RelationshipStatus.PENDING
                     except UserRelationship.DoesNotExist:
                         is_friend = is_friend_pending = False
                 return is_self, is_friend, is_friend_pending
             User.get_relationship_status = get_relationship_status

    lhs = models.ForeignKey(User, related_name="userrelationship_lhs_set")
    rhs = models.ForeignKey(User, related_name="userrelationship_rhs_set")
    status = models.IntegerField(choices=RelationshipStatus.choices)
    date_confirmed = models.DateTimeField(null=True)
    lhs_notes = models.TextField()
    rhs_notes = models.TextField()

Visibility = utils.Enum({'PUBLIC': (1, "Everyone"),
                         'PROTECTED': (2, "Me and my friends"),
                         'PRIVATE': (3, "Myself only")})

def is_visible(visibility, user, other):
    if visibility == Visibility.PUBLIC:
        return True
    elif visibility == Visibility.PROTECTED:
        if user == other:
            return True
        else:
            _, is_friend, _ = user.get_relationship_status(other)
            return is_friend
    elif visibility == Visibility.PRIVATE:
        return user == other

templates/_help_wiki_syntax.html
<h4>Formatting</h4>
<ol>
<li>Separate paragraphs by one or more blank lines.</li>
<li>To create a heading, use dashes to underline it. Like this:
<pre>
My Title
--------
</pre>
</p>
<li>To create a list, use asterisks at the beginning of every element. Like this:
<pre>
* First thing
* Second thing
* Yet another one
</pre>
</li>
<li>To create a link, use the following syntax:<pre>[Google homepage](http://google.com/)</pre></li>
<li>To create <em>italic</em> or <strong>bold</strong> text, use: <code>*italic*</code> and <code>**bold**</code> respectively.</li>
<li>Inline HTML is <strong>not</strong> allowed.</li>
</ol>

templates/account_profile.html
{% extends "page.html" %}

{% block script %}

function connect_dialog_OK()
{
    $("#id_scan_existing_tweets").val($("#connect-dialog input[name='scan-existing-tweets']:checked").val());
    $("#connect form").submit();
}

function connect_dialog_Cancel()
{
    $("#connect-dialog").dialog('close');
}

function profile_connect_click()
{
    var twitter_username = $("#id_twitter_username").val();
    if(twitter_username && twitter_username != old_twitter_username)
    {
        $("#connect-dialog").dialog('open');
    }
    else
    {
        $("#connect form").submit();
    }
}

$(function() {
    $("#account-profile-tabs").tabs().show();
    $("#connect-dialog").dialog({autoOpen: false, modal: true, buttons: {"OK": connect_dialog_OK, "Cancel": connect_dialog_Cancel}});
    old_twitter_username = $("#id_twitter_username").val(); // JS::global-var
});

{% endblock %}

{% block content %}
<div class="column span-10 prepend-7 prepend-top">

<div id="account-profile-tabs" style="display: none">
<ul>
  <li><a href="#profile"><span>Profile</span></a></li>
  <li><a href="#connect"><span>Connect</span></a></li>
</ul>

<div id="profile">
<form method="POST" action="" enctype="multipart/form-data">
{{ form.as_p }}
<p><input type="submit" class="submit button positive" value="Save" /></p>
</form>
</div>

<div id="connect">
<form method="POST" action="/account/profile/connect/">
{{ connect_form.as_p }}
<p><input type="button" class="button positive" value="Save" onclick="javascript:profile_connect_click();" /></p>
<div id="connect-dialog">
  <p>Do you want to scan and import your existing tweets? <a href="/help/twitter/" target="_blank">Read this</a> for help.</p>
  <p>
    <input type="radio" id="scan-existing-tweets-1" name="scan-existing-tweets" value="1" checked="checked" />
    <label for="scan-existing-tweets-1">Yes. Scan and import my existing tweets and any future tweets.</label>
  </p>
  <p>
    <input type="radio" id="scan-existing-tweets-0" name="scan-existing-tweets" value="0" />
    <label for="scan-existing-tweets-0">No. Scan and import only my future tweets.</label>
  </p>
</div>
</form>
</div>

</div>
</div>
{% endblock %}

templates/annotation_view.html
{% extends "base.html" %}

{% block body %}

<p>
{{ annotation.ui.render }}
</p>

<a class="navigation" href="/trip/{{ annotation.trip.id }}/annotation/all/">Back to annotation list</a>

{% endblock %}

templates/help_faq.html
{% extends "page.html" %}

{% block content %}
<div class="column span-15 prepend-5 prepend-top">
  <h3>Frequently asked questions</h3>
  <p>
    Q: <a name="trip_id">What is the ID of a trip?</a><br />
    A: The ID of a trip is a number that uniquely identifies the trip within traveli.st. To find out what the ID of a trip is, go to the trip's page and look at your browser's address bar. It's the number you see just after "/trips/" and before the dash.<br /> <img src="{{ MEDIA_URL }}images/static/help/trip-id.png" alt="" /> 
  </p>
  <p>
    Q: <a name="twitter">Does traveli.st integrate with Twitter?</a><br />
    A: Yes. See <a href="/help/twitter/">this</a>. 
  </p>
  <p>
    Q: <a name="flickr">Does traveli.st integrate with Flickr?</a><br />
    A: Yes. See <a href="/help/flickr/">this</a>. 
  </p>
</div>
{% endblock %}

templates/help_flickr.html
{% extends "page.html" %}

{% block content %}
<div class="column span-15 prepend-5 prepend-top">
  <h3>Flickr support in traveli.st</h3>
  <h4>How it works?</h4>
  <ol>
    <li>If you don't have a Flickr account yet, <a href="http://flickr.com/">create one</a>.</li>
    <li>Go to your <a href="/account/profile/">profile</a> and on the "Connect" tab set your Flickr user ID. Use <a href="http://idgettr.com/">idGettr</a> to find out what your user ID is.</li>
    <li>That's it. Now whenever you go on a trip just post anything you want to Flickr. If you want a photo to be associated to your trip, just tag it with "travelist:trip=TRIP_ID" (replace TRIP_ID with <a href="/help/faq/#trip-id">the ID of your trip</a>) and it will show up on your trip's page, on the "Photos" tab.</li>
  </ol>
</div>
{% endblock %}

templates/notification_list.html
{% extends "page.html" %}

{% load cachedfile %}

{% block htmlhead %}
<script src="{{ MEDIA_URL }}{% cachedfile "javascript/c/notification.js" %}" type="text/javascript"></script>
<script type="text/javascript">
$(notification_list_init);
</script>
{% endblock %}

{% block content %}
<div class="column span-15 prepend-5 prepend-top">
{% if notifications %}
<ul id="notification-list" class="plain-list">
  {% for notification in notifications %}
  <li id="notification-{{ notification.id }}" data-notification_type="{{ notification.manager.type_name }}">
    {{ notification.date|date }}, {% autoescape off %}{{ notification.manager.render }}{% endautoescape %}
    {% for action in notification.manager.available_actions_choices %}
      <input type="button" class="button {{ action.class }}" value="{{ action.description }}" onclick="javascript:dispatch_action({{ notification.id }}, {{ action.id }}, '{{ action.name }}');" />
    {% endfor %}
  </li>
  {% endfor %}
</ul>
{% else %}
You have no notifications.
{% endif %}
</div>
{% endblock %}

templates/place.html
{% extends "page.html" %}

{% load cachedfile %}
{% load call %}
{% load markup %}

{% block htmlhead %}
<meta name="ICBM" content="{{ place.coords.coords.0|floatformat:3 }}, {{ place.coords.coords.1|floatformat:3 }}" />
<meta name="geo.position" content="{{ place.coords.coords.0|floatformat:3 }}; {{ place.coords.coords.1|floatformat:3 }}" />
<meta name="geo.placename" content="{{ place.display_name }}" />
<script src="http://maps.google.com/maps?file=api&amp;v=2&amp;key={{ settings.GOOGLE_MAPS_API_KEY }}" type="text/javascript"></script>
<script src="{{ MEDIA_URL }}{% cachedfile "javascript/c/google-maps-all.js" %}" type="text/javascript"></script>
<script src="{{ MEDIA_URL }}javascript/place.js" type="text/javascript"></script>
{% endblock %}

{% block script %}
$(function() { initPlaceMap({{ place.coords.coords.0 }}, {{ place.coords.coords.1 }}, "{{ place.name }}"); });
{% endblock %}

{% block content %}
<div class="column span-14 prepend-5 prepend-top">
  <h3>{{ place.display_name }}</h3>
  <div class="geo">Coordinates: <span class="latitude">{{ place.coords.coords.0|floatformat:2 }}</span>; <span class="longitude">{{ place.coords.coords.1|floatformat:2 }}</span></div>
  <div id="place-map"></div>
  <br />
  <div>
    {% if place.wiki_content %}
      {{ place.wiki_content|force_escape|urlize|markdown }}
    {% else %}
      {% if not user.is_anonymous %}
        We don't have a description for this place yet, <a href="/places/{{ place.id }}/edit/">care to help</a>?
      {% endif %}
    {% endif %}
  </div>
  <hr />
  {% call "_star_rating.html" with entity=place %}
  <div>
    <h4>Comments</h4>
    {% if not user.is_anonymous %}
      <div>
        <form action="/places/{{ place.id }}/comments/new/" method="POST">
          <textarea name="comment_content" style="height: 60px;"></textarea><br />
          <input type="submit" class="submit button positive" value="Say it!" />
        </form>
      </div>
      <br />
    {% endif %}
    {% for comment in place.placecomment_set.all %}
      <div>
        <a href="/people/{{ comment.user.username }}">{{ comment.user.username }}</a>
        said on {{ comment.date_added|date }}:
        {% ifequal comment.user user %}(<a href="javascript:delete_comment({{ place.id }}, {{ comment.id }});">delete</a>){% endifequal %}
        {{ comment.content|markdown:"safe" }}
      </div>
    {% empty %}
      <span>No user comments yet!</span>
    {% endfor %}
  </div>
</div>
<div class="column span-3 prepend-2 prepend-top last">
<p>
{% if place.wiki_content and not user.is_anonymous %}
<a href="/places/{{ place.id }}/edit/">Edit</a>
{% endif %}
</p>
<p>

</p>
</div>
{% endblock %}

templates/place_edit.html
{% extends "page.html" %}

{% block content %}

<div class="column span-14 prepend-4 prepend-top">
<h3>{{ place.display_name }}</h3>
  <form action="" method="POST">
    <fieldset>
      {{ form.as_p }}
      <p>
        <input type="submit" class="submit button positive" value="Save" />
        <input type="button" class="button negative" value="Cancel" onclick="javascript:window.location='{{ place.get_absolute_url }}';" />
      </p>
    </fieldset>
  </form>
</div>
<div class="column span-6 prepend-top last">
{% include "_help_wiki.html" %}
{% include "_help_wiki_syntax.html" %}
</div>
{% endblock %}

templates/suggestion_new.html
{% extends "page.html" %}
{% block content %}
<div class="column span-10 prepend-7 prepend-top">
<form method="POST" action="">
<fieldset>
<legend>Send a suggestion</legend>
{{ form.as_p }}
<p><input type="submit" class="submit button positive" value="Send" /></p>
</fieldset>
</form>
</div>
{% endblock %}

templates/trip_edit.html
{% extends "page.html" %}

{% load cachedfile %}

{% block htmlhead %}
<script src="{{ MEDIA_URL }}{% cachedfile "javascript/c/trip.js" %}" type="text/javascript"></script>
{% endblock %}

{% block script %}
$(init_trip_edit);
{% endblock %}

{% block content %}
<div class="column span-8 prepend-8 prepend-top last">
  <form id="trip-info" action="" method="POST">
    <fieldset>
    <legend>{% if trip.id %}Edit{% else %}New{% endif %} trip</legend>
    {{ form.as_p }}
    <p>
      <input type="submit" class="submit button positive" value="Save" />
      {% if trip.id %}
      <input type="button" class="button negative" value="Cancel" onclick="javascript:window.location='{{ trip.get_absolute_url }}';" />
      {% else %}
      <input type="button" class="button negative" value="Cancel" onclick="javascript:window.location='/trips/{{ user.username }}/';" />
      {% endif %}
    </p>
    </fieldset>
  </form>
</div>
{% endblock %}

templates/trip_list.html
{% extends "page.html" %}

{% block content %}
<div class="column span-14 prepend-5 prepend-top">
{% if trips %}
<h3>{% if is_self %}My{% else %}{{ for_user.username }}&apos;s{% endif %} trips</h3>
<table id="trip-list" class="data-grid prepend-top">
  <thead>
    <td width="35%">Name</td>
    <td width="20%">Start date</td>
    <td width="20%">End date</td>
    <td width="25%" class="lastcolumn"></td>
  </thead>
  {% for trip in trips %}
  <tr{% if forloop.first %} class="firstrow"{% endif %}>
    <td class="firstcolumn"><a href="{{ trip.get_absolute_url }}">{{ trip.name }}</a></td>
    <td>{{ trip.start_date|date }}</td>
    <td>{{ trip.end_date|date }}</td>
    <td class="lastcolumn" style="text-align: center;">{% for t in trip.transportations %}<img width="14" heigth="14" src="/media/images/transportation/{{ t.0 }}.png" title="{{ t.1 }}" />{% endfor %}</td>
  </tr>
  {% endfor %}
</table>
{% else %}
<div class="large">
{% if is_self %}
You have no trips. Start by <a href="/trips/new/">adding one</a>.
{% else %}
User {{ for_user.username }} has no trips.
{% endif %}
</div>
{% endif %}
</div>
{% if is_self %}
<div class="column span-3 prepend-2 prepend-top last">
  {% if trips %}
  <a href="/trips/new/" class="large" style="position: relative; top: 100px;">add a trip</a>
  {% endif %}
</div>
{% endif %}
{% endblock %}

templates/user_friends.html
{% extends "page.html" %}
{% load call %}

{% block content %}
{% for friend in for_user.get_friends %}
  {% call "user_badge.html" with for_user=friend is_self=0 is_friend=1 is_friend_pending=0 %}
{% endfor %}
{% endblock %}

templates/user_profile.html
{% extends "page.html" %}
{% load call %}

{% block content %}
{% call "user_badge.html" %}

{% endblock %}